<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Zend Framework Quickstart Application</title>
  <?php echo $this->headLink() ?>
  
  <?php echo $this->headStyle() ?>
  
  <?php echo $this->headScript() ?>
  </head>
<body>
	<nav class="navbar navbar-default" role="navigation">
	<div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">ZFQuickstart</a>
      </div>
    
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
  			<li class="active"><a href="<?php echo $this->url(array('controller'=>'guestbook'),'default',true) ?>">Guestbook</a></li>
  		</ul>
      </div><!-- /.navbar-collapse -->
    </div>
    </nav>
    <div class="container">
    
        
      <div class="content">
        <div class="page-header">
          <h1>Zend Framework Guestbook application</h1>
        </div>
		<?php echo $this->layout()->content ?>
      </div>

      <footer>
      </footer>
    </div> <!-- /container -->
</body>
</html>
            